= Functions

== Learning Material

A *function* is a block of code which only runs when it is called. You can pass
data, known as _parameters_, into a function. A function can return data as a
result.

=== Creating a Function

In Python a function is defined using the `def` keyword:

[source,python]
----
def my_function():
    print("Hello from a function")
----

=== Calling a Function

To call a function, use the function name followed by parenthesis:

[source,python]
----
def my_function():
    print("Hello from a function")

my_function() ## Output: Hello from a function
----

=== Parameters

Information can be passed to functions as parameter.

Parameters are specified after the function name, inside the parentheses. You
can add as many parameters as you want, just separate them with a comma.

The following example has a function with one parameter (_fname_). When the
function is called, we pass along a first name, which is used inside the
function to print the full name:

[source,python]
----
def my_function(fname):
    print(fname + " Refsnes")

my_function("Emil") ## Output: Emil Refsnes
my_function("Tobias") ## Output: Tobias Refsnes
my_function("Linus") ## Output: Linus Refsnes
----

=== Default Parameter Value

The following example shows how to use a default parameter value. If we call the
function without parameter, it uses the default value:

[source,python]
----
def my_function(country = "Norway"):
    print("I am from " + country)

my_function("Sweden") ## Output: I am from Sweden
my_function("India") ## Output: I am from India
my_function() ## Output: I am from Norway
my_function("Brazil") ## Output: I am from Brazil
----

=== Passing a List as a Parameter

You can send any data types of parameter to a function (_string, number, list,
dictionary etc._), and it will be treated as the same data type inside the
function.

E.g. if you send a `list` as a parameter, it will still be a `list` when it
reaches the function:

[source,python]
----
def my_function(food):
    for x in food:
        print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)
----

=== Return Values

To let a function return a value, use the `return` statement:

[source,python]
----
def my_function(x):
    return 5 * x

print(my_function(3)) ## Output: 15
print(my_function(5)) ## Output: 25
print(my_function(9)) ## Output: 45
----

=== Keyword Arguments

You can also send arguments with the `key = value` syntax. This way the order of
the arguments does not matter.

[source,python]
----
def my_function(child3, child2, child1):
    print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")
## Output: The youngest child is Linus
----

=== Arbitrary Arguments

If you do not know how many arguments will be passed into your function, add a
`*` before the parameter name in the function definition.

This way the function will receive a tuple of arguments, and can access the
items accordingly:

[source,python]
----
def my_function(*kids):
    print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")
## Output: The youngest child is Linus
----


== Exercises

=== 1. Say Hello

Write a function called greetings(name) that returns a string of
characters. This function will take as argument a variable name. This
function will return a string `Hello name'

=== 2. Count employees

Create a function `sum_of_employees()` that calculates and returns the
number of students in a list. The function will have to return an
integer.

=== 3. Is divisible ?

Create a function is_divisible(n, x, y) that checks if a number n is
divisible by two numbers x AND y. All inputs are positive, non-zero
digits.

Example:

....
is_divisible(3,1,3)--> True because 3 is divisible by 1 and 3
is_divisible(12,2,6)--> True because 12 is divisible by 2 and 6
is_divisible(100,5,3)--> False because 100 is not divisible by 3
is_divisible(12,7,5)--> False because 12 is neither divisible by 7 nor 5
....


=== 4. Abbreviate a multiple words Company Name

Write a function to convert a company name into an acronym. This
function strickly takes multiple words with one space in between them.

Example :

....
Bayerische Motoren Werk => B.M.W.
Ingvar Kamprad Elmtaryd Agunnaryd => I.K.E.A.
American Standard Code Information Interchange => A.S.C.I.I.
....


=== 5. Sum of positive

You get an array of numbers, return the sum of all of the even ones.

Example : +
`[4, 8, 15, 16, 23, 42] => 4 + 8 + 16 + 42 = 70`


=== 6. Sum mixed array

Given an array of integers as strings and numbers, return the sum of the
array values as if all were numbers.

Return your answer as a number.

Example :

....
sum_mix(['5', '0', 9, 3, 2, 1, '9', 6, 7]) => 42
....


=== 7. Return the month Complete the function which returns the month
according to the input number:

....
1 returns "January"
2 returns "February"
3 returns "March"
4 returns "April"
5 returns "May"
6 returns "June"
7 returns "July"
8 returns "August"
9 returns "September"
10 returns "October"
11 returns "November"
12 returns "December"
Otherwise returns "Wrong, please enter a number between 1 and 12"
....


=== 8. Product

Write a program that finds the product of every number from 1 to num.
The number will always be a positive integer greater than 0.

Example :

....
    product(2) -> 2
    1 x 2

    product(4) -> 24
    1 x 2 x 3 x 4
....


=== 9. If you can’t sleep, just count sheep!!

Given a non-negative integer, 3 for example, return a string with a
murmur: `1 sheep…2 sheep…3 sheep…`. Input will always be valid,
i.e. no negative integers.


=== 10. Employee’s salary

Create a function salary_calculator, which calculates the monthly salary
of an employee depending on two parameters: the education and the
seniority.

This function should take two arguments: education (`Highschool` -
`University` - `BeCode`); seniority - years inside the company (from 0
and above);

This function should return a number (salary). There are four types of
salaries:

....
1 000 000 euros , if the education is BeCode or if the seniority is more than 100.
90 000 euros, if the education is University and if the seniority is at least 25.
50 000 euros, if the degree is Highschool and if the seniority is at least 5.
2 euros in other cases
....
