= Conditions

== Learning Material

=== The conditional construct

The notion of *conditions* is one of the most important in programming. It
introduces logic and allows the creation of _algorithms_.

The idea behind the construct is to express something like this:

----
- If the variable is equal to something then do this.
    - Do an action
- If not, do this.
    - Do an action
----

Python uses boolean variables to evaluate conditions. The boolean values `True`
and `False` are returned when an expression is compared or evaluated. For
example:

[source,python]
----
x = 2
print(x == 2) # prints out True
print(x == 3) # prints out False
print(x < 3) # prints out True
----

The simplest conditional construct would be a single `if` statement.

[source,python]
----
age = 23
if age >= 18:
    print("You're an adult!")
----

However, you can _complexify_ the construct and allow for multiple conditional
checks with the `elif` statement. The key word `elif` is a contraction of the
words "else if".

[source,python]
----
age = 17
if age >= 18:
    print("You're an adult!")
elif age == 17 :
    print("You are one year short of being an adult")
----

It is also possible to give instructions which will be executed only if the
condition is not met. To do so you can use the `else` statement.

[source,python]
----
age = 16
if age >= 18:
    print("You're an adult!")
elif age == 17:
    print("You are one year short of being an adult")
else:
    print("Come back later")
----

=== Logical operators

As mentioned before _Python_ conditional statements works with evaluating a
condition that is either `True` or `False`. That being said, you can also use
*logical operators* like `and`, `or` and `not` in order to evaluate multiple
condition on a single statement.

The `and` operator checks if all the conditions are `True`.

[source,python]
----
student1 = "John"
student2 = "Eric"

if student1 == "John" and student2 == "Eric":
    print("You are John AND Eric")   
else :
    print("Welcome anonymous")
----

The `or` operator checks if at least one condition is `True`.

[source,python]
----
student1 = "John"
student2 = "Ludovic"

if student1 == "John" or student2 == "Eric":
    print("Your name is either John or Eric.")
else :
    print("Welcome anonymous")
----

The `in` operator could be used to check if a specified object exists within an
iterable object container, such as a list.

[source,python]
----
name = "Valérian"
coach = ["Valérian", "Ludovic"]
if name in coach:
    print("Your are Coach!")
else :
    print("You are not coach")
----

Using `not` before a boolean expression inverts it:

[source,python]
----
print(not False) # Prints out True
print((not False) == (False)) # Prints out False

name = "Ayaan"
if name not in ["Valérian", "Ludovic"]:
    print("Your are not coach")
else :
    print("You are coach")
----

Unlike the double equals operator `==`, the `is` operator does not match the
values of the variables, but the instances themselves. For example:

[source,python]
----
x = [1,2,3]
y = [1,2,3]
print(x == y) # Prints out True
print(x is y) # Prints out False
----

But this operator will be further explained later.
