= Conditions

== Learning Material

=== The conditional construct

The notion of *conditions* is one of the most important in programming. It
introduces logic and allows the creation of _algorithms_.

The idea behind the construct is to express something like this:

----
- If the variable is equal to something then do this.
    - Do an action
- If not, do this.
    - Do an action
----

Python uses boolean variables to evaluate conditions. The boolean values `True`
and `False` are returned when an expression is compared or evaluated. For
example:

[source,python]
----
x = 2
print(x == 2) # prints out True
print(x == 3) # prints out False
print(x < 3) # prints out True
----

Notice that variable assignment is done using a single equal operator `=`,
whereas comparison between two variables is done using the double equals
operator `==`. The "not equals" operator is marked as `!=`.

Python uses indentation to define code blocks, instead of brackets. The standard
Python indentation is 4 spaces, although tabs and any other space size will
work, as long as it is consistent. Notice that code blocks do not need any
termination.

The simplest conditional construct would be a single `if` statement.

[source,python]
----
age = 23
if age >= 18:
    print("You're an adult!")
----

However, you can _complexify_ the construct and allow for multiple conditional
checks with the `elif` statement. The key word `elif` is a contraction of the
words "else if".

[source,python]
----
age = 17
if age >= 18:
    print("You're an adult!")
elif age == 17 :
    print("You are one year short of being an adult")
----

It is also possible to give instructions which will be executed only if the
condition is not met. To do so you can use the `else` statement.

[source,python]
----
age = 16
if age >= 18:
    print("You're an adult!")
elif age == 17:
    print("You are one year short of being an adult")
else:
    print("Come back later")
----

=== Logical operators

As mentioned before _Python_ conditional statements works with evaluating a
condition that is either `True` or `False`. That being said, you can also use
*logical operators* like `and`, `or` and `not` in order to evaluate multiple
condition on a single statement.

The `and` operator checks if all the conditions are `True`.

[source,python]
----
student1 = "John"
student2 = "Eric"

if student1 == "John" and student2 == "Eric":
    print("You are John AND Eric")   
else :
    print("Welcome anonymous")
----

The `or` operator checks if at least one condition is `True`.

[source,python]
----
student1 = "John"
student2 = "Ludovic"

if student1 == "John" or student2 == "Eric":
    print("Your name is either John or Eric.")
else :
    print("Welcome anonymous")
----

The `in` operator could be used to check if a specified object exists within an
iterable object container, such as a list.

[source,python]
----
name = "Valérian"
coach = ["Valérian", "Ludovic"]
if name in coach:
    print("Your are Coach!")
else :
    print("You are not coach")
----

Using `not` before a boolean expression inverts it:

[source,python]
----
print(not False) # Prints out True
print((not False) == (False)) # Prints out False

name = "Ayaan"
if name not in ["Valérian", "Ludovic"]:
    print("Your are not coach")
else :
    print("You are coach")
----

Unlike the double equals operator `==`, the `is` operator does not match the
values of the variables, but the instances themselves. For example:

[source,python]
----
x = [1,2,3]
y = [1,2,3]
print(x == y) # Prints out True
print(x is y) # Prints out False
----

But this operator will be further explained later.


== Exercises

In some of these exercises, you will have to use methods that you have not seen
yet. In this case, search on _google_ for an example of use. Take the right
habits to avoid being blocked.

*1. Create a variable `age` that contains value 55*


*2. Adds 10 to variable `age`*


*3. Create a variable `div_age` and assign it the value of the age
divided by 5* +
- ❗ Be careful, it must be an integer.


*4. Create a variable `text_div` that contains the character string ``65
divided by 5 is equal 11''.* +
- You must use the `age` and `div_age` variables


*5. Create a variable `rest_div` that contains the rest of the variable
`age` divided by 7*


*6. Create a variable `exp_div` that contains the value of `rest_div`
exponent 3*


*7. Write a program that enters an integer and then displays the value
entered and its type.*


*8. Use variables to represent the price of materials.* +
- 2 cokes at 2.20€ each - 3 Gin & Tonic at 8.60€ each - 1 Goat cheese
salad at 11.70€ - 2 steaks with fries at 18€ each - 2 spaghetti
bolognese at 14.80€ each

*Calculate the sum of all items and store it in a `restaurant_bill`
variable*


*Create a variable `wallet` which has a value of 120 and then create an
algorithm that calculates the available money by subtracting the price
of the order.*

If there is enough money, record the following sentence in the variable
`message` and subtract the expense from `wallet` : - message = ``You
have spent'' + `restaurant_bill` + ``you have left'' + `wallet`

If there is not enough money, record the following sentence in the
`message` variable: - message= ``Sorry you’re missing _amount_missing_
euros''

If there is 0 left, record the following sentence in the `message`
variable: - message = ``You are broke!''


*9. Write a program that asks you to enter 2 values and displays the
highest of the 2 values*


*10. Write a script that asks you to enter 2 strings and displays the
shortest of the 2 strings (the one with the least characters).*


*11. Write a script that converts centimeters into inches.* - The
program will start by asking the user to indicate with characters `cm'
or `in'. - Then the program will ask you to enter the value and display
the conversion.


*12. Check if the variable `ingredient` is in the `bloody_mary` list.
(Without making a loop)* * If the ingredient is in the list, display
``You can put some into the glass''. * Otherwise display: ``Please don’t
put this into the glass…''


*13. Calculate the volume of a sphere using the formula _(4π/3) x R³_.
The radius is 7.* +
- Save the result in a ``volume'' variable.
