= Functions

== Learning Material

A *function* is a block of code which only runs when it is called. You can pass
data, known as _parameters_, into a function. A function can return data as a
result.

=== Creating a Function

In Python a function is defined using the `def` keyword:

[source,python]
----
def my_function():
    print("Hello from a function")
----

=== Calling a Function

To call a function, use the function name followed by parenthesis:

[source,python]
----
def my_function():
    print("Hello from a function")

my_function() ## Output: Hello from a function
----

=== Parameters

Information can be passed to functions as parameter.

Parameters are specified after the function name, inside the parentheses. You
can add as many parameters as you want, just separate them with a comma.

The following example has a function with one parameter (_fname_). When the
function is called, we pass along a first name, which is used inside the
function to print the full name:

[source,python]
----
def my_function(fname):
    print(fname + " Refsnes")

my_function("Emil") ## Output: Emil Refsnes
my_function("Tobias") ## Output: Tobias Refsnes
my_function("Linus") ## Output: Linus Refsnes
----

=== Default Parameter Value

The following example shows how to use a default parameter value. If we call the
function without parameter, it uses the default value:

[source,python]
----
def my_function(country = "Norway"):
    print("I am from " + country)

my_function("Sweden") ## Output: I am from Sweden
my_function("India") ## Output: I am from India
my_function() ## Output: I am from Norway
my_function("Brazil") ## Output: I am from Brazil
----

=== Passing a List as a Parameter

You can send any data types of parameter to a function (_string, number, list,
dictionary etc._), and it will be treated as the same data type inside the
function.

E.g. if you send a `list` as a parameter, it will still be a `list` when it
reaches the function:

[source,python]
----
def my_function(food):
    for x in food:
        print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)
----

=== Return Values

To let a function return a value, use the `return` statement:

[source,python]
----
def my_function(x):
    return 5 * x

print(my_function(3)) ## Output: 15
print(my_function(5)) ## Output: 25
print(my_function(9)) ## Output: 45
----

=== Keyword Arguments

You can also send arguments with the `key = value` syntax. This way the order of
the arguments does not matter.

[source,python]
----
def my_function(child3, child2, child1):
    print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")
## Output: The youngest child is Linus
----

=== Arbitrary Arguments

If you do not know how many arguments will be passed into your function, add a
`*` before the parameter name in the function definition.

This way the function will receive a tuple of arguments, and can access the
items accordingly:

[source,python]
----
def my_function(*kids):
    print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")
## Output: The youngest child is Linus
----
