= Challenges

== 1. Write the beer song.

Not all the verses are the same. ``` 99 bottles of beer on the wall, 99
bottles of beer. Take one down and pass it around, 98 bottles of beer on
the wall.

98 bottles of beer on the wall, 98 bottles of beer. Take one down and
pass it around, 97 bottles of beer on the wall.

97 bottles of beer on the wall, 97 bottles of beer. Take one down and
pass it around, 96 bottles of beer on the wall.

…

…

2 bottles of beer on the wall, 2 bottles of beer. Take one down and pass
it around, 1 bottle of beer on the wall.

1 bottle of beer on the wall, 1 bottle of beer. Take it down and pass it
around, no more bottles of beer on the wall.

No more bottles of beer on the wall, no more bottles of beer. Go to the
store and buy some more, 99 bottles of beer on the wall.```


== 2. Meet Joe

Joe answers `'Sure.'` if you ask him a question.

He answers `'Whoa, chill out!'` if you yell at him.

He answers `'Calm down, I know what I'm doing!'` if you do both.

He says `'Fine. Be that way!'` if you address him without actually
saying anything.

He answers `'Whatever.'` to anything else.


== 3. Leap year

The tricky thing here is that a leap year in the Gregorian calendar
occurs:

[source,plain]
----
on every year that is evenly divisible by 4
  except every year that is evenly divisible by 100
    unless the year is also evenly divisible by 400
----

For example, 1997 is not a leap year, but 1996 is. 1900 is not a leap
year, but 2000 is.

If your language provides a method in the standard library that does
this look-up, pretend it doesn’t exist and implement it yourself.



== 4. Check Phone number

The rules are as follows:

* If the phone number is less than 10 digits assume that it is bad
number
* If the phone number is 10 digits assume that it is good
* If the phone number is 11 digits and the first number is 1, trim the 1
and use the last 10 digits
* If the phone number is 11 digits and the first number is not 1, then
it is a bad number
* If the phone number is more than 11 digits assume that it is a bad
number

We’ve provided tests, now make them pass.
