= Python Reskilling

The main goal of the *Python Reskilling* is to allow people to learn the
_fundamentals_ of Python in *three days*. This repository contains different
*modules* (_presentations_, _lessons_, _exercices_) to acquire the basics, as
well as, a small *project* to _test_ your newly acquired knowledge.

In order for the _reskilling_ to be both *useful* and *productive* we decided to
put the *rules* below in place.

|===
| Rule | Why?

| _Speak English_
| For better communication everyone will have to speak in English.

| _No speed-run_
| The content as been prepared to cover three days, no need to go faster than
the coaches.

| _Be punctual_
| To respect the schedule that as been thought out you should arrive on time.

| _Learn together_
| Although you could do everything on your own, you should try to help or ask
for the help of your colleagues.
|===


== Modules

During the two first days we will focus on *acquiring the fundamentals*. Below,
you will find links to the different sections we are going to explore.

Each module will be composed of at least a *presentation* (_given by the
coaches_), *learning material* (_you read on your own_) and *exercises* (_will
be corrected in groups with the coaches_).

* link:./[Introduction]
* link:./[Conditions]
* link:./[Loops and Iterator]
* link:./[Tuples and Dictionaries]
* link:./[Functions]

NOTE: We will try to see as many *good practices* (ex: _PEP8_) as possible, but
feel free to _research_ on your own and share with the group.


== Project

The last day will be reserved to *work on a project* in small groups of _two_.
You can find the instructions for the challenge link:./project[here].


== Useful links

* https://docs.python.org/3/[documentation]
