= Python Reskilling

// Links
:presentation: https://docs.google.com/presentation/d/1P-u7CudtLAWlwYTZ93chSBreieEaBNesAib6XV7BRQY/edit?usp=sharing

The main goal of the *Python Reskilling* is to allow people to learn the
_fundamentals_ of Python in *three days*. This repository contains different
*modules* (_learning material_, _exercises_) to acquire the basics, as well as,
a small *project* to _test_ your newly acquired knowledge. You can also find a
file containing additional challenges link:./challenges.adoc[here], feel free
to explore it *if you have time* between _modules_.

In order for the _reskilling_ to be both *useful* and *productive* we decided to
put the *rules* below in place.

|===
| Rule | Why?

| _Speak English_
| For better communication and in order for the coaches to understand your
needs, everyone will have to speak in English.

| _No speed-running_
| The content as been prepared to cover three days, no need to go faster than
the coaches or your colleagues.

| _Be punctual_
| To respect the schedule that as been thought out you should arrive on time.

| _Learn together_
| Although you could do everything on your own, you should try to help or ask
for the help of your colleagues.
|===


== Modules

During the two first days we will focus on *acquiring the fundamentals*. Below,
you will find links to the different sections we are going to explore.

Each module will be composed of at least a *presentation* (_given by the
coaches_), *learning material* (_you read on your own_) and *exercises* (_will
be corrected in groups with the coaches_).

* link:./modules/1.introduction.adoc[1. Introduction]
* link:./modules/2.conditions.adoc[2. Conditions]
* link:./modules/3.loops.adoc[3. Loops and Iterator]
* link:./modules/4.lists.adoc[4. Tuples and Dictionaries]
* link:./modules/5.functions.adoc[5. Functions]

NOTE: We will try to see as many *good practices* (ex: _PEP8_) as possible, but
feel free to _research_ on your own and share with the group.


== Project

The last day will be reserved to *work on a project* in small groups of _two_.

1. The Hangman

Create a Hangman Game, the program should take as argument a word and give you the chance to guess the word with a specific amount of tries.

2. Wordy

Step 1
----
What is 5 plus 13?
----
The program should handle large numbers and negative numbers.
Remember, that these are verbal word problems, not treated as you normally would treat a written problem. This means that you calculate as you move forward each step. In other words, you should ignore order of operations. 3 + 2 * 3 = 15, not 9.
Use the tests to drive your solution by deleting the skip in one test at a time.

Step 2
----
What is 5 plus 13?
What is 7 minus 5?
What is 6 multiplied by 4?
What is 25 divided by 5?
----
Step 3
----
What is 5 plus 13 plus 6?
What is 7 minus 5 minus 1?
What is 9 minus 3 plus 5?
What is 3 plus 5 minus 8?
----
Step 4
----
What is 5 plus 13?
What is 7 minus 5?
What is 6 times 4?
What is 25 divided by 5?
What is 78 plus 5 minus 3?
What is 18 times 3 plus 16?
What is 4 times 3 divided by 6?
What is 4 plus 3 times 2?
----



== Useful links

* {presentation}[presentation]
* https://docs.python.org/3/[documentation]
* https://www.python.org/dev/peps/pep-0008/[pep 8]
